name: Build and Test

on:
  push:
    branches:
        - master
        - '[0-9]+.[0-9]+.[0-9]+'
        - '[0-9]+.[0-9]+'
  pull_request:
    branches: 
        - master
        - '[0-9]+.[0-9]+.[0-9]+'
        - '[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-ubuntu:
    uses: ./.github/workflows/BUILD_LINUX_REUSABLE.yml

  build-and-test-mac:
    uses: ./.github/workflows/BUILD_MAC_REUSABLE.yml
