name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-ubuntu:

    uses: ./.github/workflows/BUILD_LINUX_REUSABLE.yml
    with:
      v8_version: default

  build-and-test-mac:

    uses: ./.github/workflows/BUILD_MAC_REUSABLE.yml
    with:
      v8_version: default
