name: Nightly master build

on:

  workflow_dispatch:

  schedule:
    - cron: "0 5 * * *"

jobs:
  build-and-test-ubuntu:

    uses: ./.github/workflows/BUILD_LINUX_REUSABLE.yml
    with:
      v8_version: main
      v8_update_headers: yes

  build-and-test-mac:

    uses: ./.github/workflows/BUILD_MAC_REUSABLE.yml
    with:
      v8_version: main
      v8_update_headers: yes
