name: Update Version

on:
  workflow_dispatch:
    inputs:
      v8_version:
        description: 'The version to update to'
        type: string
        required: true

jobs:

  update-v8-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Getting V8 version
      id: get-current-v8-version
      run: |
        export V8_VERSION_CURRENT=`cat ./V8_DEFAULT_VERSION.txt`
        echo "V8_VERSION_CURRENT=$V8_VERSION_CURRENT" >> "$GITHUB_OUTPUT"
    - name: Check new version is geater than current version
      env:
        V8_VERSION_CURRENT: ${{ steps.get-current-v8-version.outputs.V8_VERSION_CURRENT }}
      if: ${{ env.V8_VERSION_CURRENT >= inputs.v8_version }}
      run: |
        echo new version ${{ inputs.v8_version }} is not greater then current version ${{ env.V8_VERSION_CURRENT }}
        exit 1
    - name: Update Version
      run: echo ${{ inputs.v8_version }} > ./V8_DEFAULT_VERSION.txt
    - name: Build
      run: V8_UPDATE_HEADERS=${{ inputs.v8_update_headers }} cargo build -vv
    - name: Run tests
      run: V8_UPDATE_HEADERS=${{ inputs.v8_update_headers }} cargo test -vv
    - name: Create PR if needed
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git config --global user.email "auto@redis.com"
        git config --global user.name "auto user"
        git checkout -b auto_update_version_to_${{ inputs.v8_version }}
        git add ./V8_DEFAULT_VERSION.txt
        git add ./v8_c_api/src/v8include/*
        git commit -m "Auto update version to ${{ inputs.v8_version }}"
        git push origin auto_update_version_to_${{ inputs.v8_version }}
        gh pr create --title "Auto update version to ${{ inputs.v8_version }}" --body "Generated by GitHub action" --reviewer MeirShpilraien,vityafx
